### ISSUE TITLE
[HELP WANTED]

### ISSUE THREAD

**Issue by NerdyRanger** [DarkKronicle/AdvancedChatMacros#2]
so i dont know if im doing something wrong, but i get 

`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install kommandlib, any version.
Unmet dependency listing:
	 - Mod 'AdvancedChatMacros' (advancedchatmacros) 1.18.2-1.0.0 requires any version of kommandlib, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
`
as an error, when launghing this mod. it says i need any version of kommand lib and i am unable to find any details on it.

**Comment by DarkKronicle** [comment]
What versions of the mods are you using? Macros doesn't have a 1.19 version yet if you're trying to use it in 1.19

**Comment by NerdyRanger** [comment]
I actually just looked at that, and guess it probably is because I'm running 1.19 everything else. Am I able to get macros running if I downgrade the other mods, while on 1.19 or are there important changes that will not be compatible with 1.19

**Comment by DarkKronicle** [comment]
1.18 versions will not work with 1.19. When I get some free time again I plan on updating macros.

**Comment by NerdyRanger** [comment]
ok, I thank you for your time, I may take a look at it my self and see if it something I can do, sorry for my silly questions.
